#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: f4a13a5a93c1
#
Name     : xsane
Version  : 0.999
Release  : 2
URL      : https://gitlab.com/sane-project/frontend/xsane/-/archive/0.999/xsane-0.999.tar.bz2
Source0  : https://gitlab.com/sane-project/frontend/xsane/-/archive/0.999/xsane-0.999.tar.bz2
Summary  : An X Window System front-end for the SANE scanner interface.
Group    : Development/Tools
License  : GPL-2.0
Requires: xsane-bin = %{version}-%{release}
Requires: xsane-data = %{version}-%{release}
Requires: xsane-locales = %{version}-%{release}
Requires: xsane-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(gimp-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(zlib)
BuildRequires : sane-backends-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-fedora-xsane-0.995-xdg-open.patch
Patch2: backport-fedora-xsane-0.995-close-fds.patch
Patch3: backport-fedora-xsane-0.996-no-eula.patch
Patch4: backport-fedora-xsane-0.997-off-root-build.patch
Patch5: backport-fedora-xsane-0.999-no-file-selected.patch
Patch6: backport-fedora-xsane-0.997-ipv6.patch
Patch7: backport-fedora-xsane-0.998-preview-selection.patch
Patch8: backport-fedora-xsane-0.998-libpng.patch
Patch9: backport-fedora-xsane-0.998-wmclass.patch
Patch10: backport-fedora-xsane-0.998-desktop-file.patch
Patch11: backport-fedora-xsane-0.999-man-page.patch
Patch12: backport-fedora-xsane-0.999-pdf-no-high-bpp.patch
Patch13: backport-fedora-xsane-0.999-lcms2.patch
Patch14: backport-fedora-xsane-0.999-coverity.patch
Patch15: backport-fedora-xsane-0.999-snprintf-update.patch
Patch16: backport-fedora-xsane-0.999-signal-handling.patch
Patch17: backport-fedora-0001-Follow-new-convention-for-registering-gimp-plugin.patch
Patch18: backport-fedora-xsane-configure-c99.patch

%description
XSane is an X based interface for the SANE (Scanner Access Now Easy)
library, which provides access to scanners, digital cameras, and other
capture devices. XSane is written in GTK+ and provides control for
performing the scan and then manipulating the captured image.

%package bin
Summary: bin components for the xsane package.
Group: Binaries
Requires: xsane-data = %{version}-%{release}

%description bin
bin components for the xsane package.


%package data
Summary: data components for the xsane package.
Group: Data

%description data
data components for the xsane package.


%package locales
Summary: locales components for the xsane package.
Group: Default

%description locales
locales components for the xsane package.


%package man
Summary: man components for the xsane package.
Group: Default

%description man
man components for the xsane package.


%prep
%setup -q -n xsane-0.999
cd %{_builddir}/xsane-0.999
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
%patch -P 6 -p1
%patch -P 7 -p1
%patch -P 8 -p1
%patch -P 9 -p1
%patch -P 10 -p1
%patch -P 11 -p1
%patch -P 12 -p1
%patch -P 13 -p1
%patch -P 14 -p1
%patch -P 15 -p1
%patch -P 16 -p1
%patch -P 17 -p1
%patch -P 18 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736468976
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --enable-gimp
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1736468976
rm -rf %{buildroot}
export GOAMD64=v2
GOAMD64=v2
%make_install
%find_lang xsane

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xsane

%files data
%defattr(-,root,root,-)
/usr/share/applications/xsane.desktop
/usr/share/pixmaps/xsane.xpm
/usr/share/sane/xsane/Mustek-logo.xpm
/usr/share/sane/xsane/Plustek-logo.xpm
/usr/share/sane/xsane/UMAX-logo.xpm
/usr/share/sane/xsane/doc/sane-backends-doc.html
/usr/share/sane/xsane/doc/sane-pnm-doc.html
/usr/share/sane/xsane/doc/sane-problems-doc.html
/usr/share/sane/xsane/doc/sane-scantips-doc.html
/usr/share/sane/xsane/doc/sane-xsane-advanced-doc.html
/usr/share/sane/xsane/doc/sane-xsane-batch-scan-doc.html
/usr/share/sane/xsane/doc/sane-xsane-color-correction-doc.html
/usr/share/sane/xsane/doc/sane-xsane-color-management-doc.html
/usr/share/sane/xsane/doc/sane-xsane-copy-doc.html
/usr/share/sane/xsane/doc/sane-xsane-doc.html
/usr/share/sane/xsane/doc/sane-xsane-email-doc.html
/usr/share/sane/xsane/doc/sane-xsane-empty-doc.html
/usr/share/sane/xsane/doc/sane-xsane-fax-doc.html
/usr/share/sane/xsane/doc/sane-xsane-gimp-doc.html
/usr/share/sane/xsane/doc/sane-xsane-guide-doc.html
/usr/share/sane/xsane/doc/sane-xsane-histogram-doc.html
/usr/share/sane/xsane/doc/sane-xsane-medium-definition-doc.html
/usr/share/sane/xsane/doc/sane-xsane-multipage-doc.html
/usr/share/sane/xsane/doc/sane-xsane-preview-doc.html
/usr/share/sane/xsane/doc/sane-xsane-save-doc.html
/usr/share/sane/xsane/doc/sane-xsane-scan-options-doc.html
/usr/share/sane/xsane/doc/sane-xsane-setup-color-management-doc.html
/usr/share/sane/xsane/doc/sane-xsane-setup-copy-doc.html
/usr/share/sane/xsane/doc/sane-xsane-setup-display-doc.html
/usr/share/sane/xsane/doc/sane-xsane-setup-email-doc.html
/usr/share/sane/xsane/doc/sane-xsane-setup-enhancement-doc.html
/usr/share/sane/xsane/doc/sane-xsane-setup-fax-doc.html
/usr/share/sane/xsane/doc/sane-xsane-setup-filetype-doc.html
/usr/share/sane/xsane/doc/sane-xsane-setup-save-doc.html
/usr/share/sane/xsane/doc/sane-xsane-standard-doc.html
/usr/share/sane/xsane/doc/sane-xsane-viewer-doc.html
/usr/share/sane/xsane/doc/xsane-adf-pages.jpg
/usr/share/sane/xsane/doc/xsane-advanced.jpg
/usr/share/sane/xsane/doc/xsane-aspect-ratio.jpg
/usr/share/sane/xsane/doc/xsane-autoenhance.jpg
/usr/share/sane/xsane/doc/xsane-autoraise_scanarea.jpg
/usr/share/sane/xsane/doc/xsane-autoselect.jpg
/usr/share/sane/xsane/doc/xsane-batch-scan-add.jpg
/usr/share/sane/xsane/doc/xsane-batch-scan-delete.jpg
/usr/share/sane/xsane/doc/xsane-batch-scan.jpg
/usr/share/sane/xsane/doc/xsane-blur.jpg
/usr/share/sane/xsane/doc/xsane-brightness.jpg
/usr/share/sane/xsane/doc/xsane-clone.jpg
/usr/share/sane/xsane/doc/xsane-cms-function.jpg
/usr/share/sane/xsane/doc/xsane-color-correction-rgb-default.jpg
/usr/share/sane/xsane/doc/xsane-color-correction.jpg
/usr/share/sane/xsane/doc/xsane-color-management-main-window.jpg
/usr/share/sane/xsane/doc/xsane-colormode.jpg
/usr/share/sane/xsane/doc/xsane-contrast.jpg
/usr/share/sane/xsane/doc/xsane-copy-number.jpg
/usr/share/sane/xsane/doc/xsane-copy.jpg
/usr/share/sane/xsane/doc/xsane-default.jpg
/usr/share/sane/xsane/doc/xsane-delete-preview-cache.jpg
/usr/share/sane/xsane/doc/xsane-despeckle.jpg
/usr/share/sane/xsane/doc/xsane-disk.jpg
/usr/share/sane/xsane/doc/xsane-edit-medium.jpg
/usr/share/sane/xsane/doc/xsane-email-project.jpg
/usr/share/sane/xsane/doc/xsane-email.jpg
/usr/share/sane/xsane/doc/xsane-enable-color-management.jpg
/usr/share/sane/xsane/doc/xsane-fax-project.jpg
/usr/share/sane/xsane/doc/xsane-fax.jpg
/usr/share/sane/xsane/doc/xsane-gamma.jpg
/usr/share/sane/xsane/doc/xsane-gimp.jpg
/usr/share/sane/xsane/doc/xsane-guide-1-decoration.jpg
/usr/share/sane/xsane/doc/xsane-guide-10-scan.jpg
/usr/share/sane/xsane/doc/xsane-guide-2-menu.jpg
/usr/share/sane/xsane/doc/xsane-guide-3-options.jpg
/usr/share/sane/xsane/doc/xsane-guide-4.jpg
/usr/share/sane/xsane/doc/xsane-guide-4a-adf-pages.jpg
/usr/share/sane/xsane/doc/xsane-guide-4b-xsane-mode.jpg
/usr/share/sane/xsane/doc/xsane-guide-5-saving-options.jpg
/usr/share/sane/xsane/doc/xsane-guide-6-scan-options.jpg
/usr/share/sane/xsane/doc/xsane-guide-7-medium-selection.jpg
/usr/share/sane/xsane/doc/xsane-guide-8-resolution.jpg
/usr/share/sane/xsane/doc/xsane-guide-9-color-correction.jpg
/usr/share/sane/xsane/doc/xsane-histogram.jpg
/usr/share/sane/xsane/doc/xsane-logo.jpg
/usr/share/sane/xsane/doc/xsane-medium-add.jpg
/usr/share/sane/xsane/doc/xsane-medium.jpg
/usr/share/sane/xsane/doc/xsane-mirror-x.jpg
/usr/share/sane/xsane/doc/xsane-mirror-y.jpg
/usr/share/sane/xsane/doc/xsane-multipage-project.jpg
/usr/share/sane/xsane/doc/xsane-multipage.jpg
/usr/share/sane/xsane/doc/xsane-negative.jpg
/usr/share/sane/xsane/doc/xsane-new.jpg
/usr/share/sane/xsane/doc/xsane-ocr.jpg
/usr/share/sane/xsane/doc/xsane-open.jpg
/usr/share/sane/xsane/doc/xsane-paper-landscape-bottom-left.jpg
/usr/share/sane/xsane/doc/xsane-paper-landscape-bottom-right.jpg
/usr/share/sane/xsane/doc/xsane-paper-landscape-center.jpg
/usr/share/sane/xsane/doc/xsane-paper-landscape-top-left.jpg
/usr/share/sane/xsane/doc/xsane-paper-landscape-top-right.jpg
/usr/share/sane/xsane/doc/xsane-paper-portrait-bottom-left.jpg
/usr/share/sane/xsane/doc/xsane-paper-portrait-bottom-right.jpg
/usr/share/sane/xsane/doc/xsane-paper-portrait-center.jpg
/usr/share/sane/xsane/doc/xsane-paper-portrait-top-left.jpg
/usr/share/sane/xsane/doc/xsane-paper-portrait-top-right.jpg
/usr/share/sane/xsane/doc/xsane-pipette-black.jpg
/usr/share/sane/xsane/doc/xsane-pipette-gray.jpg
/usr/share/sane/xsane/doc/xsane-pipette-white.jpg
/usr/share/sane/xsane/doc/xsane-preferences.jpg
/usr/share/sane/xsane/doc/xsane-preset-area-context-menu.jpg
/usr/share/sane/xsane/doc/xsane-preset-area.jpg
/usr/share/sane/xsane/doc/xsane-preview.jpg
/usr/share/sane/xsane/doc/xsane-printer.jpg
/usr/share/sane/xsane/doc/xsane-rename.jpg
/usr/share/sane/xsane/doc/xsane-resolution.jpg
/usr/share/sane/xsane/doc/xsane-restore.jpg
/usr/share/sane/xsane/doc/xsane-rgb-default.jpg
/usr/share/sane/xsane/doc/xsane-rgb-values.jpg
/usr/share/sane/xsane/doc/xsane-rotate-180.jpg
/usr/share/sane/xsane/doc/xsane-rotate-270.jpg
/usr/share/sane/xsane/doc/xsane-rotate-90.jpg
/usr/share/sane/xsane/doc/xsane-rotation.jpg
/usr/share/sane/xsane/doc/xsane-save.jpg
/usr/share/sane/xsane/doc/xsane-save2.jpg
/usr/share/sane/xsane/doc/xsane-scale.jpg
/usr/share/sane/xsane/doc/xsane-scansource.jpg
/usr/share/sane/xsane/doc/xsane-setup-color-management.jpg
/usr/share/sane/xsane/doc/xsane-setup-copy.jpg
/usr/share/sane/xsane/doc/xsane-setup-display.jpg
/usr/share/sane/xsane/doc/xsane-setup-email.jpg
/usr/share/sane/xsane/doc/xsane-setup-enhancement.jpg
/usr/share/sane/xsane/doc/xsane-setup-fax.jpg
/usr/share/sane/xsane/doc/xsane-setup-filetype.jpg
/usr/share/sane/xsane/doc/xsane-setup-ocr.jpg
/usr/share/sane/xsane/doc/xsane-setup-save.jpg
/usr/share/sane/xsane/doc/xsane-standard.jpg
/usr/share/sane/xsane/doc/xsane-step.jpg
/usr/share/sane/xsane/doc/xsane-store.jpg
/usr/share/sane/xsane/doc/xsane-target.jpg
/usr/share/sane/xsane/doc/xsane-threshold.jpg
/usr/share/sane/xsane/doc/xsane-viewer-window.jpg
/usr/share/sane/xsane/doc/xsane-viewer.jpg
/usr/share/sane/xsane/doc/xsane-visible-area.jpg
/usr/share/sane/xsane/doc/xsane-zoom-in.jpg
/usr/share/sane/xsane/doc/xsane-zoom-not.jpg
/usr/share/sane/xsane/doc/xsane-zoom-out.jpg
/usr/share/sane/xsane/doc/xsane-zoom-undo.jpg
/usr/share/sane/xsane/doc/xsane-zoom.jpg
/usr/share/sane/xsane/sane-epson-logo.xpm
/usr/share/sane/xsane/sane-hp-logo.xpm
/usr/share/sane/xsane/sane-umax-logo.xpm
/usr/share/sane/xsane/sane-xsane-logo.xpm
/usr/share/sane/xsane/xsane-calibration.pnm
/usr/share/sane/xsane/xsane-eula.txt
/usr/share/sane/xsane/xsane-gpl.txt
/usr/share/sane/xsane/xsane-logo.xpm
/usr/share/sane/xsane/xsane-startimage.pnm
/usr/share/sane/xsane/xsane-style.rc

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xsane.1

%files locales -f xsane.lang
%defattr(-,root,root,-)

